import Foundation

public struct Localizer {
    
    private static let strings: [String: [String: String]] = [
        "ko": [
            "cancel": "취소",
            "send": "전송",
            "done": "완료",
            "all_photos": "모든 사진",
            "selected": "선택됨",
            "recents": "최근 항목",
            "confirm": "확인",
            "enter_text": "텍스트를 입력해 주세요",
            "text": "텍스트",
            "delete_edits_title": "편집 취소",
            "delete_edits_message": "편집을 삭제 하시겠습니까?",
            "yes": "예",
            "no": "아니오",

            "album_recents": "최근 항목",
            "album_favorites": "즐겨찾기",
            "album_selfies": "셀피",
            "album_live_photos": "Live Photo",
            "album_panoramas": "파노라마",
            "album_timelapses": "타임랩스",
            "album_slow_mo": "슬로모션",
            "album_videos": "비디오",
            "album_screenshots": "스크린샷",
            "album_recently_added": "최근 추가됨",
            "album_bursts": "연사",
            "album_portrait": "인물 사진",
            "album_default": "앨범",

            "crop_freeform": "자유롭게",
            "effect": "효과",
            "filter_original": "원본",
            "filter_soft": "부드러운",
            "filter_clean": "깨끗한",
            "filter_winter": "그 겨울",
            "filter_warm": "따스한",
            "filter_shining": "빛나는",
            "filter_mono": "흑백",
            "filter_vintage": "빈티지",
            "filter_fade": "페이드",
            "filter_dramatic": "극적인",
            "filter_fresh": "싱그러운",
            "filter_vibrant": "생동감",
            "filter_cinematic": "영화같은",
            "filter_instant": "아날로그",
            "filter_noir": "누아르",
            "filter_process": "프로세스",
            "filter_tonal": "토널",
            "filter_transfer": "트랜스퍼",
            "filter_chrome": "크롬",
            "filter_vignette": "비네팅",
            "editor_apply": "적용"


        ],
        "en": [
            "cancel": "Cancel",
            "send": "Send",
            "done": "Done",
            "all_photos": "All Photos",
            "selected": "Selected",
            "recents": "Recents",
            "confirm": "Confirm",
            "enter_text": "Enter text",
            "text": "Text",
            "delete_edits_title": "Cancel Edit",
            "delete_edits_message": "Are you sure you want to delete the edits?",
            "yes": "Yes",
            "no": "No",

            "album_recents": "Recents",
            "album_favorites": "Favorites",
            "album_selfies": "Selfies",
            "album_live_photos": "Live Photos",
            "album_panoramas": "Panoramas",
            "album_timelapses": "Timelapses",
            "album_slow_mo": "Slow Motion",
            "album_videos": "Videos",
            "album_screenshots": "Screenshots",
            "album_recently_added": "Recently Added",
            "album_bursts": "Bursts",
            "album_portrait": "Portrait Photos",
            "album_default": "Album",

            "crop_freeform": "Free",
            "effect": "Effect",
            "filter_original": "Original",
            "filter_soft": "Soft",
            "filter_clean": "Clean",
            "filter_winter": "Winter",
            "filter_warm": "Warm",
            "filter_shining": "Shining",
            "filter_mono": "Mono",
            "filter_vintage": "Vintage",
            "filter_fade": "Fade",
            "filter_dramatic": "Dramatic",
            "filter_fresh": "Fresh",
            "filter_vibrant": "Vibrant",
            "filter_cinematic": "Cinematic",
            "filter_instant": "Instant",
            "filter_noir": "Noir",
            "filter_process": "Process",
            "filter_tonal": "Tonal",
            "filter_transfer": "Transfer",
            "filter_chrome": "Chrome",
            "filter_vignette": "Vignette",
            "editor_apply": "Apply"


        ],
        "ja": [
            "cancel": "キャンセル",
            "send": "送信",
            "done": "完了",
            "all_photos": "すべての写真",
            "selected": "選択済み",
            "recents": "最近の項目",
            "confirm": "確認",
            "enter_text": "テキストを入力してください",
            "text": "テキスト",
            "delete_edits_title": "編集をキャンセル",
            "delete_edits_message": "編集を削除しますか？",
            "yes": "はい",
            "no": "いいえ",

            "album_recents": "最近の項目",
            "album_favorites": "お気に入り",
            "album_selfies": "セルフィー",
            "album_live_photos": "Live Photos",
            "album_panoramas": "パノラマ",
            "album_timelapses": "タイムラプス",
            "album_slow_mo": "スローモーション",
            "album_videos": "ビデオ",
            "album_screenshots": "スクリーンショット",
            "album_recently_added": "最近追加した項目",
            "album_bursts": "バースト",
            "album_portrait": "ポートレート",
            "album_default": "アルバム",

            "effect": "効果",
            "filter_original": "オリジナル",
            "filter_soft": "ソフト",
            "filter_clean": "クリーン",
            "filter_winter": "冬",
            "filter_warm": "暖かい",
            "filter_shining": "輝く",
            "filter_mono": "モノクロ",
            "filter_vintage": "ヴィンテージ",
            "filter_fade": "フェード",
            "filter_dramatic": "ドラマチック",
            "filter_fresh": "フレッシュ",
            "filter_vibrant": "鮮やか",
            "filter_cinematic": "シネマティック",
            "filter_instant": "インスタント",
            "filter_noir": "ノワール",
            "filter_process": "プロセス",
            "filter_tonal": "トナル",
            "filter_transfer": "トランスファー",
            "filter_chrome": "クローム",
            "filter_vignette": "ビネット",
            "editor_apply": "適用"


        ],
        "zh": [
            "cancel": "取消",
            "send": "发送",
            "done": "完成",
            "all_photos": "所有照片",
            "selected": "已选择",
            "recents": "最近项目",
            "confirm": "确认",
            "enter_text": "请输入文本",
            "text": "文字",
            "delete_edits_title": "取消编辑",
            "delete_edits_message": "确定要删除编辑吗？",
            "yes": "是",
            "no": "否",

            "album_recents": "最近项目",
            "album_favorites": "个人收藏",
            "album_selfies": "自拍",
            "album_live_photos": "实况照片",
            "album_panoramas": "全景照片",
            "album_timelapses": "延时摄影",
            "album_slow_mo": "慢动作",
            "album_videos": "视频",
            "album_screenshots": "截屏",
            "album_recently_added": "最近添加",
            "album_bursts": "连拍快照",
            "album_portrait": "人像",
            "album_default": "相簿",

            "effect": "效果",
            "filter_original": "原图",
            "filter_soft": "柔和",
            "filter_clean": "清晰",
            "filter_winter": "冬日",
            "filter_warm": "温暖",
            "filter_shining": "闪耀",
            "filter_mono": "黑白",
            "filter_vintage": "复古",
            "filter_fade": "褪色",
            "filter_dramatic": "戏剧",
            "filter_fresh": "清新",
            "filter_vibrant": "生动",
            "filter_cinematic": "电影",
            "filter_instant": "拍立得",
            "filter_noir": "黑白电影",
            "filter_process": "冲印",
            "filter_tonal": "色调",
            "filter_transfer": "岁月",
            "filter_chrome": "铬黄",
            "filter_vignette": "晕影",
            "editor_apply": "应用"


        ]
    ]
    
    public static func getString(key: String, languageCode: String) -> String {
        // Find exact match first
        if let langDict = strings[languageCode], let value = langDict[key] {
            return value
        }
        
        // Fallback to English
        if let enDict = strings["en"], let fallback = enDict[key] {
            return fallback
        }
        
        // Final fallback is the key itself
        return key
    }
}
